In [2]:
import numpy as np
import scipy

In [8]:
# Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
print(np.arange(1, 11))

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
print(np.zeros((3, 3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
# Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
np.random.randint(1, 11, size=(5, 5))

array([[ 3, 10, 10,  2,  5],
       [ 4,  6,  2,  9,  6],
       [ 8,  5,  3,  6,  4],
       [ 4, 10, 10,  5,  8],
       [ 2, 10,  6,  7,  1]])

In [17]:
# Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
np.random.rand(4, 4)

array([[0.06305766, 0.55784621, 0.54351449, 0.25478141],
       [0.96316431, 0.72807536, 0.31625493, 0.72258567],
       [0.24392054, 0.31247784, 0.53806088, 0.38989375],
       [0.27136722, 0.60524523, 0.63676783, 0.52799925]])

In [31]:
# Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
first_array =  np.random.randint(1, 11, size=5)
second_array =  np.random.randint(1, 11, size=5)

plus = first_array + second_array
minus = first_array - second_array
multiply = first_array * second_array
print(first_array)
print(second_array)

print(plus)
print(minus)
print(multiply)

[3 1 7 6 2]
[6 7 7 1 1]
[ 9  8 14  7  3]
[-3 -6  0  5  1]
[18  7 49  6  2]


In [15]:
# Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
vector1 = np.random.randint(1, 101, size=7)
vector2 = np.random.randint(1, 101, size=7)

print(vector1)
print(vector2)
print(np.dot(vector1, vector2))

[48 17 52 35 14 35  7]
[12 78 20 17 10 63 72]
6386


In [6]:
# Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

print(np.dot(matrix1, matrix2))

[[ 45  84  77]
 [ 72 135 126]]


In [10]:
# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
matrix = np.random.randint(1, 11, size=(3, 3))

print(np.linalg.inv(matrix))

[[ 0.41666667  1.75       -1.66666667]
 [ 0.5         3.5        -3.        ]
 [-0.66666667 -4.          3.66666667]]


In [13]:
# Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
matrix = np.random.rand(4, 4)

print(np.transpose(matrix))

[[0.48132897 0.53154914 0.24984241 0.42038968]
 [0.34302429 0.77584993 0.45611169 0.75587841]
 [0.0944493  0.31924201 0.04231792 0.45529332]
 [0.89401972 0.09943106 0.28893001 0.38744106]]


In [17]:
# Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=4)

print(np.dot(matrix, vector))

[133  93  82]


In [20]:
# Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
matrix = np.random.rand(2, 3)
vector = np.random.random(3)

print(np.dot(matrix, vector))

[0.54767806 0.09454484]


In [22]:
# Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print(np.multiply(matrix1, matrix2))

[[ 6 42]
 [63 10]]


In [23]:
# Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

print(np.dot(matrix1, matrix2))

[[29 28]
 [15 62]]


In [4]:
# Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
matrix = np.random.randint(1, 101, size=(5, 5))
print(np.sum(matrix))

1293


In [5]:
# Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
matrix1 = np.random.randint(1, 101, size=(4, 4))
matrix2 = np.random.randint(1, 101, size=(4, 4))

print(matrix1 - matrix2)

[[-60  37   0 -76]
 [-20  -9  11 -40]
 [ 26  46   5  38]
 [-73 -67  78  18]]


In [7]:
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
matrix = np.random.rand(3, 3)

print(matrix)
row_sums = np.sum(matrix, axis=1, keepdims=True)
print(row_sums)

[[0.39729021 0.13893907 0.27997992]
 [0.32732724 0.99885978 0.08301925]
 [0.33227844 0.05338056 0.03884611]]
[[0.8162092 ]
 [1.40920628]
 [0.42450511]]


In [11]:
# Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
matrix = np.random.randint(1, 10, size=(3, 4))
print(matrix)
print(np.square(matrix))

[[1 4 3 2]
 [6 2 8 4]
 [4 8 5 4]]
[[ 1 16  9  4]
 [36  4 64 16]
 [16 64 25 16]]


In [13]:
# Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
vector = np.random.randint(1, 51, size=4)

print(vector)
print(np.sqrt(vector))

[43 30 31 40]
[6.55743852 5.47722558 5.56776436 6.32455532]
